.TH "Formel X" 1 "February 2011" "" "Linux User's Manual"

.SH NAME
formel-x \- slot car lap counter

.SH SYNOPSIS
.B formel-x
\".RI [ options ]
.br

.SH DESCRIPTION
\fBFormel X\fP is slot car lap counter.
.TP
It is written in gambas2.

\".SH OPTIONS
\".IP \fB\-OPTION\fP
\"This option...

.SH FILES
.TP
.I ${HOME}/.formel-x/
Configurations directory.

.SH BUGS
Report bugs to http://code.google.com/p/formel-x/issues

.SH NOTES
This manpage was written to solve lintian warning. If there are any questions 
how to use \fBFormel X\fP please read program documentation.